Bootstrap: docker
From: ubuntu:18.04

%labels
    Maintainer Belcour A.
    Version v0.1.0
    Description EsMeCaTa Singularity recipe

%environment
    export PATH=/opt/conda/bin:${PATH}

%post
	apt-get update && \
    apt-get update && apt-get -y upgrade
    apt-get -y install \
    git \
	wget ;\
    rm -rf /var/lib/apt/lists/* ;\
    apt-get clean ;\
    wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh ;\
    /bin/bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local ;\
    conda update conda ;\
    conda install mmseqs2 pandas sparqlwrapper requests biopython ete3 -c conda-forge -c bioconda;\
    python3 -c 'from ete3 import NCBITaxa; ncbi = NCBITaxa()';\
	pip install esmecata
