name: test_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - mmseqs2
  - pandas=1.5.3
  - sparqlwrapper
  - requests
  - biopython
  - eggnog-mapper
  - orsum
  - gseapy
  - plotly
  - datapane
  - python-kaleido
  - pytest
  - pytest-mock