# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'article_data/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'esmecata.svg'
      - 'esmecata_workflow.png'
      - 'LICENSE'
      - 'recipes/**'
      - 'tutorials/**'
      - 'pictures/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'article_data/**'
      - 'README.md'
      - 'esmecata.svg'
      - 'esmecata_workflow.png'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'recipes/**'
      - 'tutorials/**'
      - 'pictures/**'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Path to brew
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        brew update
        brew install mmseqs2
        mmseqs -h
        pip install -e . --config-settings editable_mode=compat
    - name: Test with pytest
      run: |
        pip install pytest
        cd test
        pytest test_proteomes.py
        pytest test_clustering.py
        pytest test_annotation.py
        pytest test_workflow.py
        pytest test_precomputed.py
